Fix for compilation error with the Cray compilers.
The Cray compilers produce the following error:

            c_dimnames(j) = c_loc(strings(j) % str)
                                               ^
ftn-1693 crayftn: ERROR SMIOLF_DEFINE_VAR, File = smiolf.F90, Line = 550, Column = 48
  Argument must have the TARGET attribute.

According to the Fortran 2003 standard, section 5.2.1.14:

If an object has the TARGET attribute, then all of its nonpointer subobjects also
have the TARGET attribute.

So, defining 'strings' with the ALLOCATABLE and TARGET attribute causes
strings(j) % str to inherit the TARGET attribute.